databases:
  - name: bdr-postgres
    databaseName: bdr_production
    user: bdr_user
    region: singapore

services:
  - type: web
    name: bdr-app
    runtime: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bdr-postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: RAILS_MAX_THREADS
        value: 5
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: TOSS_CLIENT_KEY
        sync: false
      - key: TOSS_SECRET_KEY
        sync: false
      - key: PLATFORM_FEE_PERCENTAGE
        value: 5.0