services:
  - type: web
    name: bdr-app
    runtime: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec puma -t 5:5 -p ${PORT:-3000} -e production"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled