services:
  - type: web
    name: bdr-app
    runtime: ruby
    buildCommand: "bundle install --deployment --without development test && bundle exec rake assets:precompile"
    startCommand: "bundle exec rails server -b 0.0.0.0 -p ${PORT:-3000}"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: enabled
      - key: RAILS_SERVE_STATIC_FILES
        value: enabled